server:
  port: 8080

mybatis-plus:
  type-aliases-package: com.czp.haoyou.entity.*                             # 所有Entity别名类所在包
  mapper-locations: classpath*:/mapper/**/*.xml                             # mapper映射文件
  configuration:
    map-underscore-to-camel-case: true                                      # 开启驼峰命名自动映射
    cache-enabled: true                                                     # 开启二级缓存

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/haoyou?serverTimezone=GMT%2B8
    username: root
    password: 123456
    druid:                                                                  # 下面为连接池的补充设置，应用到上面所有数据源中
      initial-size: 5                                                       # 初始化大小
      min-idle: 5                                                           # 最小
      max-active: 20                                                        # 最大
      max-wait: 60000                                                       # 配置获取连接等待超时的时间
      stat-view-servlet:                                                    # 配置监控服务器
        enabled: true
        login-username: admin
        login-password: 123456
        url-pattern: /druid/*
        reset-enable: false

  freemarker:
    cache: true

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

  redis:
    client-type: jedis